name: Wardrovia
description: "E-commerce Mobile App Project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  cloud_firestore: ^5.6.11
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/top_selling/
    - assets/images/new_in/
    - .env